name: Code Check

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev/*
    - chore/*
    - feature/*

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ANSIBLE: false
